models.py
from .ext import db
from .util import enc_pwd

class User(db.Model):
    id = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True
    )
    name = db.Column(
        db.String(30),
        nullable=True
    )
    email = db.Column(
        db.String(30),
        unique=True,
        index=True
    )
    pwd = db.Column(
        db.String(255),
        nullable=False
    )
    is_active = db.Column(
        db.Boolean,
        default=False
    )
    is_delete = db.Column(
        db.Boolean,
        default=False
    )


    @classmethod
    def creat_user(cls, email, pwd, name=None):
#         email 能不能搜到一个用户 检查email
        users = User.query.filter(User.email==email)
        if users.count() > 0:
            # raise Exception("该Email以被使用")
            return None
#         加密密码
        user_pwd = enc_pwd(pwd)
#     创建用户
        name = name if name else email
        user = cls(
            name=name,
            email=email,
            pwd=user_pwd
        )
        db.session.add(user)
        db.session.commit()
        return user

    # 设置密码
    def set_pwd(self, pwd):
        if not pwd or len(pwd) == 0:
            raise Exception("密码不能为空")
        # 先对密码进行加密 再赋值
        self.pwd = enc_pwd(pwd)
        # 保存到数据库
        db.session.add(self)
        db.session.commit()
        return True


    # 检测密码
    def check_pwd(self, pwd):
        u_pwd = enc_pwd(pwd)
        # 比对密码
        if u_pwd == self.pwd:
            return True
        else:
            return False

class Goods(db.Model):
    __tablename__ = "axf_goods"

    id = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True
    )
    productid = db.Column(
        db.String(20)
    )
    productimg = db.Column(
        db.String(255)
    )
    productname = db.Column(
        db.String(130),
        nullable=True
    )
    productlongname = db.Column(
        db.String(190)
    )
    isxf = db.Column(
        db.Boolean,
        default=False
    )
    pmdesc = db.Column(
        db.Integer,
    )
    specifics = db.Column(
        db.String(40)
    )
    price = db.Column(
        db.Numeric(precision=10, scale=2)
    )
    marketprice = db.Column(
        db.Numeric(precision=10, scale=2)
    )
    categoryid = db.Column(
        db.Integer
    )
    childcid = db.Column(
        db.Integer
    )
    childcidname = db.Column(
        db.String(30)
    )
    dealerid = db.Column(
        db.String(30)
    )
    storenums = db.Column(
        db.Integer
    )
    productnum = db.Column(
        db.Integer
    )
    order_item_goods = db.relationship(
        "OrderItem",
        backref="goods",
        lazy=True
    )


import datetime
class Order(db.Model):
    __tablename__ = "myaxf_order"

    id = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True
    )
    user_id = db.Column(
        db.Integer,
        # db.ForeignKey("myaxf_myuser.id")
    )
    create_time = db.Column(
        db.DateTime,
        default=datetime.datetime.now()
    )
    status = db.Column(
        db.Integer
    )
    order_items = db.relationship(
        "OrderItem",
        backref="order",
        lazy=True
    )


class OrderItem(db.Model):
    __tablename__ = "myaxf_orderitem"

    id = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True
    )
    order_id = db.Column(
        db.Integer,
        db.ForeignKey("myaxf_order.id")
    )
    goods_id = db.Column(
        db.Integer,
        db.ForeignKey("axf_goods.id")
    )
    num = db.Column(
        db.Integer
    )
    buy_money = db.Column(
        db.Numeric(precision=10, scale=2)
    )



__init__.py
from flask import Flask
from myapp.ext import init_ext
from myapp.settings import config
from myapp.ulrs_apis import init_api
from myapp.views import init_blue


def create_app(env):
    app = Flask(__name__)

    # 配置
    app.config.from_object(config.get(env))

    # 做初始化第三方的插件
    init_ext(app)

    # 注册蓝图
    init_blue(app)
    # 注册restful的路由
    init_api(app)
    return app

views.py
from flask import Blueprint, render_template, request

from myapp.util import get_no_sale, get_data
from .models import *
blue = Blueprint("axfbg", __name__)

def init_blue(app):
    app.register_blueprint(blue)


# 写一些视图函数
@blue.route("/")
def item_view():
    # print(request.host_url)
    # print(request.host)
    page = request.args.get('page', 1)
    pagination = Goods.query.paginate(int(page), 8)
    return render_template("item/item.html", pagination=pagination, show=True)

@blue.route("/item_search")
def item_search():
#     参数
    kw = request.args.get("kw")
    pagination = Goods.query.filter(Goods.productlongname.contains(kw)).paginate(1, 8)

    return render_template("item/item.html", pagination=pagination, kw=kw, show=False)

@blue.route("/oder_manage")
def order_manage():
    """
        (1, "待付款"),
        (2, "已付款"),
        (3, "已发货"),
        (4, "已收货"),
        (5, "待评价"),
        (6, "已评价")

    """
    # 查所有的订单
    status_map = {
        1: "待付款",
        2: "已付款",
        3: "已发货",
        4: "已收货",
        5: "待评价",
        6: "已评价"
    }
    all_orders = Order.query.all()
    # 遍历订单 格式化时间 算钱
    for i in all_orders:
        i.created_time = i.create_time.strftime("%Y年%m月%d日 %H:%M:%S")
    #     算钱
        sum_money = 0
        for j in i.order_items:
            sum_money = sum_money + j.num * j.buy_money
        i.sum_money = sum_money
    #     将订单的状态的数字变成文字
        i.ch_status = status_map.get(i.status)

    # for i in all_orders:
    #     print("订单的id", i.id)
    #     print("订单状态", i.ch_status)
    #     print("时间", i.created_time)
    #     print("钱", i.sum_money)
    #     for j in i.order_items:
    #         print(j.goods.productlongname)




    return render_template("order/order_index.html", all_orders=all_orders)

@blue.route("/nosale")
def nosale():
    get_no_sale()
    return render_template("nosale/nosale.html")


@blue.route("/auto_bh")
def auto_bh():
    get_data()
    return render_template("auto/auto.html")

@blue.route("/index")
def index():
    return render_template("index/index.html")

@blue.route("/register")
def register_view():
    return render_template("register/register.html")

templates/active.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>激活</title>
</head>
<body>
    <h2>欢迎注册爱鲜蜂赌场，请点击下面的链接，激活您的账号，即可体验美女荷官，在线发牌</h2>
    <a href="{{ url }}">{{ url }}</a>
</body>
</html>

templates/auto/auto.html
{% extends 'base/base_main.html' %}
{% block js %}
    {{ super() }}
{#    清空所有的li的active class#}
    <script>
        $("li").removeClass("active");
        $("#auto_li").addClass("active");
    </script>
{% endblock %}

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>爱鲜蜂后台管理</title>
    {% block css %}
        <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    {% endblock %}
</head>
<body>
    {% block header %}
    
    {% endblock %}

    {% block content %}
    
    {% endblock %}
</body>
{% block js %}
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{#    <script type="text/javascript" src="{{ url_for('static', filename='js/md5.js') }}"></script>#}
{% endblock %}
</html>

templates/base/base_main.html
{% extends 'base/base.html' %}

{% block header %}
    <div class="container">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li id="item_li" class="active"><a href="{{ url_for('axfbg.item_view') }}">商品管理</a></li>
                        <li id="order_li"><a href="{{ url_for('axfbg.order_manage') }}">订单管理</a></li>
                        <li id="nosale_li"><a href="{{ url_for('axfbg.nosale') }}">不动销管理</a></li>
                        <li id="auto_li"><a href="{{ url_for('axfbg.auto_bh') }}">自动补货</a></li>

                    </ul>
                    <form class="navbar-form navbar-left" action="/item_search">
                        <div class="form-group">
                            <input type="text" class="form-control" name="kw" placeholder="请输入商品名字" id="search_kw">
                        </div>
                        <button type="submit" class="btn btn-primary" id="search_btn">搜索</button>
                    </form>
                    <ul class="nav navbar-nav navbar-right">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">我的 <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">修改密码</a></li>
                                <li><a href="#">个人资料</a></li>
                                <li><a href="#">设置</a></li>
                                <li><a href="#">退出</a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>
{% endblock %}

templates/index/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" class="ui" href="http://www.semantic-ui.cn/dist/semantic.min.css">
</head>
    <style>
         body{
            background-image: url("http://img.51miz.com/Element/00/58/78/39/59b76cc5_E587839_bdd5f2cd.jpg!/quality/90/unsharp/true/compress/true/format/jpg");
            background-repeat: no-repeat;
            background-size: 100% 100% ;
        }
    </style>
<body style="height:100%">

    <div class="container" id="con">
        <div class="ui inverted segment" style="width: 300px;margin: 200px auto;">
        <div class="ui inverted form" >
            <div class="field">
                <h2>爱鲜蜂后台管理</h2>
            </div>

            <div class="one fields" >
                <div class="field">
                    <label>账号</label>
                    <input placeholder="账号" type="text" id="email">
                </div>
            </div>

            <div class="one fields">
                <div class="field">
                    <label>密码</label>
                    <input placeholder="密码" type="password" id="pwd">
                </div>
            </div>

            <div class="ui submit button" id="login">登录</div>
            <div class="ui submit button">
                <a href="{{ url_for('axfbg.register_view') }}">注册</a>
            </div>
        </div>
        </div>
    </div>


</body>
<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</html>

templates/item/item.html
{% extends 'base/base_main.html' %}
{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='bg/item/css/item.css') }}">
{% endblock %}
{% block content %}
    <div class="container">

        <table class="table">
            <thead>
            <td>商品id</td>
            <td>商品图片</td>
            <td>商品名称</td>
            <td>商品价格</td>
            <td>商品库存</td>
            <td>操作</td>
            </thead>
            {% for i in pagination.items %}
                <tr>
                    <td>{{ i.id }}</td>
                    <td><img src="{{ i.productimg }}" alt=""></td>
                    <td>{{ i.productlongname }}</td>
                    <td>{{ i.price }}元</td>
                    <td>{{ i.storenums }}</td>
                    <td>
                        <a href="#" style="margin-top: 10px" i_id="{{ i.id }}" class="btn btn-info update_btn">修改</a>
                        <p></p>
                        <button i_id="{{ i.id }}" class="btn btn-danger delete_btn">删除</button>
                    </td>
                </tr>
            {% endfor %}
        </table>


        {% if show %}
            <nav aria-label="Page navigation">
            <ul class="pagination">
                <li>
                    <a href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>

                {# <li><a href="{{ url_for('axf_bg.get_item_view') }}?page={{ page }}">{{ page }}</a></li>#}
                {% for page in pagination.iter_pages() %}
                    {% if page %}
                        <li><a href="{{ url_for('axfbg.item_view') }}?page={{ page }}">{{ page }}</a></li>
                    {% else %}
                        {#                        <span class=ellipsis>…</span>#}
                        <li><a href="">···</a></li>
                    {% endif %}
                {% endfor %}

                <li>
                    <a href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
        {% else %}
            <nav aria-label="Page navigation">
            <ul class="pagination">
                <li>
                    <a href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>

                {# <li><a href="{{ url_for('axf_bg.get_item_view') }}?page={{ page }}">{{ page }}</a></li>#}
                {% for page in pagination.iter_pages() %}
                    {% if page %}
                        <li><a href="{{ url_for('axfbg.item_search') }}?page={{ page }}&kw={{ kw }}">{{ page }}</a></li>
                    {% else %}
                        {#                        <span class=ellipsis>…</span>#}
                        <li><a href="">···</a></li>
                    {% endif %}
                {% endfor %}

                <li>
                    <a href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
        {% endif %}
    </div>
{% endblock %}

{% block js %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='bg/item/js/item.js') }}"></script>
{% endblock %}

templates/nosale/nosale.html
{% extends 'base/base_main.html' %}

{% block js %}
    {{ super() }}
{#    清空所有的li的active class#}
    <script>
        $("li").removeClass("active");
        $("#nosale_li").addClass("active");
    </script>
{% endblock %}

templates/order/order_index.html
{% extends 'base/base_main.html' %}

{% block content %}
    <div class="container">
        <table class="table">
            <thead>
                <td>用户id</td>
                <td>订单id</td>
                <td>状态</td>
                <td>创建时间</td>
                <td>订单总金额</td>
                <td>清单</td>
                <td>操作</td>
            </thead>
            {% for i in all_orders %}
                <tr>
                    <td>{{ i.user_id }}</td>
                    <td>{{ i.id }}</td>
                    <td class="o_status">{{ i.ch_status }}</td>
                    <td>{{ i.created_time }}</td>
                    <td>{{ i.sum_money }}</td>
                    <td>
                        <ul>
                            {% for j in i.order_items %}
                                <li>{{ j.goods.productlongname }}</li>
                            {% endfor %}

                        </ul>

                    </td>
                    <td>
{#                         1: "待付款",
        2: "已付款",
        3: "已发货",
        4: "已收货",
        5: "待评价",
        6: "已评价"#}
                        <select name="" id="" o_id="{{ i.id }}">
                            <option value="1" {{ "selected" if i.status==1 }}>待付款</option>
                            <option value="2" {{ "selected" if i.status==2 }}>已付款</option>
                            <option value="3" {{ "selected" if i.status==3 }}>已发货</option>
                            <option value="4" {{ "selected" if i.status==4 }}>已收货</option>
                            <option value="5" {{ "selected" if i.status==5 }}>待评价</option>
                            <option value="6" {{ "selected" if i.status==6 }}>已评价</option>
                        </select>
                    </td>
                </tr>
            {% endfor %}

        </table>
    </div>
{% endblock %}

{% block js %}
    {{ super() }}
{#    清空所有的li的active class#}
    <script>
        $("li").removeClass("active");
        $("#order_li").addClass("active");
    </script>
    <script src="{{ url_for('static', filename='bg/order/js/order.js') }}"></script>
{% endblock %}

templates/register/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" class="ui" href="http://www.semantic-ui.cn/dist/semantic.min.css">
</head>
    <style>
        #con{
            background-image: url("http://img.51miz.com/Element/00/58/78/39/59b76cc5_E587839_bdd5f2cd.jpg!/quality/90/unsharp/true/compress/true/format/jpg");
            background-repeat: no-repeat;
            background-size: 100% 100% ;
        }
    </style>
<body>

<div class="container" id="con">
    <div class="ui inverted segment" style="width: 300px;margin: 100px auto;">
    <div class="ui inverted form" >
        <div class="one fields" >
            <div class="field">
                <label>邮箱</label>
                <input placeholder="邮箱" type="email" id="email">
            </div>
        </div>

        <div class="one fields">
            <div class="field">
                <label>密码</label>
                <input placeholder="密码" type="password" id="pwd">
            </div>
        </div>
        <div class="one fields">
            <div class="field">
                <label>确认密码</label>
                <input placeholder="确认密码" type="password" id="pwd_confirm">
            </div>
        </div>



        <div class="ui submit button">
            <button id="btn">注册</button>
        </div>
    </div>
    </div>
</div>


</body>
<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="{{ url_for('static', filename='js/md5.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename="bg/register/js/register.js") }}"></script>
</html>